title: "Andrea Munafo"
email: andrea.munafo@ieee.org
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://andreamunafo.github.io/" 
twitter_username: andreamunafo
github_username:  andreamunafo

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
